/*
   SSS, a bridge single-suit single-dummy solver.

   Copyright (C) 2020-2022 by Soren Hein.

   See LICENSE and README.
*/

#ifndef SSS_VERBALDIMENSIONS_H
#define SSS_VERBALDIMENSIONS_H


using namespace std;

#include "Slot.h"


enum VerbalGroup: unsigned
{
  GROUP_PLAYER = 0,
  GROUP_LENGTH_VERB = 1,
  GROUP_LENGTH_ORDINAL = 2,
  GROUP_COUNT = 3,
  GROUP_TOPS = 4,
  GROUP_EXCLUDING = 5,
  GROUP_BELOW = 6,
  GROUP_BOTTOMS = 7,
  GROUP_LIST = 8
};


enum VerbalPhrase: unsigned
{
  PLAYER_WEST = 0,
  PLAYER_EAST = 1,
  PLAYER_EITHER = 2,
  PLAYER_EACH = 3,
  PLAYER_NEITHER = 4,
  PLAYER_SUIT = 5,

  LENGTH_VERB_VOID = 10,
  LENGTH_VERB_XTON = 11,
  LENGTH_VERB_EVENLY = 12,
  LENGTH_VERB_ODD_EVENLY = 13,
  LENGTH_VERB_XTON_ATMOST = 14,
  LENGTH_VERB_CARDS = 15,
  LENGTH_VERB_ATMOST = 16,
  LENGTH_VERB_RANGE = 17,
  LENGTH_VERB_SPLIT = 18,

  LENGTH_ORDINAL_EXACT = 20,
  LENGTH_ORDINAL_ATMOST = 21,
  LENGTH_ORDINAL_23 = 22,

  COUNT_EXACT = 30,
  COUNT_ATMOST = 31,
  COUNT_RANGE = 32,

  TOPS_ATMOST = 40,
  TOPS_ATLEAST = 41,
  TOPS_RANGE = 42,
  TOPS_ACTUAL = 43,
  TOPS_LOWER = 44,
  TOPS_BELOW = 45,

  EXCLUDING_NONE = 50,
  EXCLUDING_NEITHER = 51,
  EXCLUDING_NOT = 52,

  BELOW_NORMAL = 60,
  BELOW_COMPLETELY = 61,

  BOTTOMS_NORMAL = 70,

  LIST_HOLDING_EXACT = 80,
  LIST_HOLDING_WITH_LOWS = 81,

  VERBAL_PHRASE_SIZE = 90
};

#endif
